#!/usr/bin/env node
// test/run.js — Games' own test runner, the shape `ov test` drives. ds-testsel calls
// `node test/run.js <test/… entries>`; each entry under test/ is a one-line pointer to a
// colocated TypeScript test, and this runs those through vitest and prints the per-file lines
// ov test parses (✓/✗ <entry> <ms>ms). With no argument it runs every vitest file (`pnpm test`).
//
// The pointers exist because Games' tests are TypeScript and colocated, not the test/*.test.js
// files the harness's runner convention expects; vitest reads the real files, so their
// @vitest-environment docblocks and imports stay exactly as written. The pointers are generated
// from the vitest include globs by `node test/run.js --index`; a missing or stale one fails the
// run rather than silently testing less.
//
//   node test/run.js                 every test file
//   node test/run.js <entry|word>…   the entries whose name matches a word
//   node test/run.js --index         (re)write the test/ pointers from the vitest include globs
import { spawnSync } from 'node:child_process'
import {
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const dir = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(dir, '..')
const POINTER = /^\/\/ file: '(.+)'$/m

/** Every file vitest.config.ts runs: the .test.ts and .audit.ts files under apps and packages. */
function vitestFiles() {
  const out = []
  const walk = (rel) => {
    for (const e of readdirSync(path.join(root, rel), { withFileTypes: true })) {
      if (e.name === 'node_modules' || e.name === 'dist' || e.name === 'dist-types') continue
      const r = `${rel}/${e.name}`
      if (e.isDirectory()) walk(r)
      else if (/\.(test|audit)\.ts$/.test(e.name)) out.push(r)
    }
  }
  for (const top of ['apps', 'packages']) if (existsSync(path.join(root, top))) walk(top)
  return out.sort()
}

/** test/<slug>.test.js for a TypeScript test: flat, so ds-testsel can list and shard them. */
function pointerName(ts) {
  const stem = ts.replace(/\.ts$/, '')
  return `${stem}${stem.endsWith('.test') ? '.js' : '.test.js'}`.replace(/\//g, '__')
}

/** The pointers in test/: entry basename → the TypeScript file it runs. */
function pointers() {
  const map = new Map()
  for (const f of readdirSync(dir).filter((f) => f.endsWith('.test.js'))) {
    const m = POINTER.exec(readFileSync(path.join(dir, f), 'utf8'))
    if (m) map.set(f, m[1].trim())
  }
  return map
}

/** Exactly one pointer per vitest file; drift fails the run rather than silently testing less. */
function check(ents, files) {
  const byTs = new Map([...ents].map(([f, ts]) => [ts, f]))
  const missing = files.filter((ts) => !byTs.has(ts))
  const stale = [...ents].filter(([, ts]) => !files.includes(ts))
  if (!missing.length && !stale.length) return true
  for (const ts of missing) {
    console.error(`test/run.js: no test/ pointer for ${ts} — run \`node test/run.js --index\``)
  }
  for (const [f, ts] of stale) {
    console.error(
      `test/run.js: ${f} points at ${ts}, which vitest no longer runs — run \`node test/run.js --index\``,
    )
  }
  return false
}

function index() {
  const files = vitestFiles()
  const want = new Map(files.map((ts) => [pointerName(ts), ts]))
  if (want.size !== files.length) {
    console.error('test/run.js: two test paths map to the same pointer name; rename one')
    process.exit(1)
  }
  // The `covers:` line is quoted so ds-testsel's path-based selection (a change in the test's own
  // directory) reaches the pointer even when the source file's name does not match the test's.
  const body = (ts) =>
    `// file: '${ts}'\n// covers: '${path.posix.dirname(ts)}'\n// Generated by node test/run.js --index; do not edit.\n`
  for (const [name, ts] of want) {
    const p = path.join(dir, name)
    if (!existsSync(p) || readFileSync(p, 'utf8') !== body(ts)) writeFileSync(p, body(ts))
  }
  let removed = 0
  for (const f of readdirSync(dir)) {
    if (!f.endsWith('.test.js') || want.has(f)) continue
    if (POINTER.exec(readFileSync(path.join(dir, f), 'utf8'))) {
      unlinkSync(path.join(dir, f))
      removed++
    }
  }
  console.log(
    `test/run.js: ${want.size} pointers written${removed ? `, ${removed} stale removed` : ''}`,
  )
}

const argv = process.argv.slice(2)
if (argv.includes('--index')) {
  index()
  process.exit(0)
}

const ents = pointers()
const files = vitestFiles()
if (!check(ents, files)) process.exit(1)

const words = argv.filter((a) => !a.startsWith('--'))
let chosen
if (!words.length) {
  chosen = [...ents.keys()]
} else {
  const set = new Set()
  for (const w of words) {
    const base = path.basename(w)
    if (ents.has(base)) {
      set.add(base)
      continue
    }
    const hits = [...ents.keys()].filter(
      (f) => f.includes(base) || f.includes(base.replace(/\.test\.js$/, '')),
    )
    if (!hits.length) {
      console.error(`test/run.js: no test/ pointer matches ${w}`)
      process.exit(1)
    }
    for (const h of hits) set.add(h)
  }
  chosen = [...set]
}

const vitest = path.join(root, 'node_modules', '.bin', 'vitest')
if (!existsSync(vitest)) {
  console.error('test/run.js: vitest is not installed — run `pnpm install`')
  process.exit(127)
}

const tsFiles = [...new Set(chosen.map((f) => ents.get(f)))].sort()
const tmp = mkdtempSync(path.join(tmpdir(), 'ov-games-test-'))
const reportFile = path.join(tmp, 'report.json')
const r = spawnSync(vitest, ['run', '--reporter=json', `--outputFile=${reportFile}`, ...tsFiles], {
  cwd: root,
  stdio: ['ignore', 'pipe', 'pipe'],
})
const vitestOut = `${r.stdout || ''}${r.stderr || ''}`.trim()
let report = null
try {
  report = JSON.parse(readFileSync(reportFile, 'utf8'))
} catch {
  // vitest died before writing the report; the captured output below says why
}
rmSync(tmp, { recursive: true, force: true })

const byAbs = new Map()
for (const t of (report && report.testResults) || []) byAbs.set(path.resolve(t.name), t)

const tails = []
let bad = 0
for (const f of chosen) {
  const ts = ents.get(f)
  const t = byAbs.get(path.resolve(root, ts))
  const failed =
    !t || t.status === 'failed' || (t.assertionResults || []).some((a) => a.status === 'failed')
  const ms = t && t.endTime != null ? Math.max(0, Math.round(t.endTime - t.startTime)) : 0
  console.log(`${failed ? '✗' : '✓'} ${f} ${ms}ms`)
  if (!failed) continue
  bad++
  const detail = !t
    ? `no vitest result for ${ts}${r.status ? ` (vitest exited ${r.status})` : ''}\n${vitestOut
        .split('\n')
        .slice(-15)
        .join('\n')}`
    : (t.assertionResults || [])
        .filter((a) => a.status === 'failed')
        .map((a) => (a.failureMessages || []).join('\n'))
        .filter(Boolean)
        .join('\n') ||
      t.message ||
      'failed'
  tails.push(`── ${f} (exit 1) ──\n${detail}`)
}
for (const tail of tails) console.log(`\n${tail}`)
process.exit(bad ? 1 : 0)
