import type { ItemDef } from '../schema/item.js'

/**
 * Item content. Tools carry a `tool` capability (what primary fire does),
 * building pieces carry `world` + `placeable`, stations add `workstation`.
 * Adding an item must never require engine changes.
 */
export const ITEMS: ItemDef[] = [
  // ── Tools ──────────────────────────────────────────────────────────
  {
    id: 'physgun',
    name: 'Physgun',
    description: 'Field manipulator. Grab, drag, rotate, freeze. The sandbox in your hands.',
    category: 'tool',
    maxStack: 1,
    tool: { kind: 'physgun', power: 1, range: 8 },
  },
  {
    id: 'stone_axe',
    name: 'Stone Axe',
    description: 'Fells trees. Crude, heavy, effective.',
    category: 'tool',
    maxStack: 1,
    tool: { kind: 'axe', power: 2, range: 3.5 },
  },
  {
    id: 'stone_pickaxe',
    name: 'Stone Pickaxe',
    description: 'Breaks stone deposits apart.',
    category: 'tool',
    maxStack: 1,
    tool: { kind: 'pickaxe', power: 2, range: 3.5 },
  },
  {
    id: 'rigging_tool',
    name: 'Rigging Tool',
    description:
      'Links props together: weld, rope, hinge, bearing, slider, spring, motor. LMB picks two points; RMB cuts everything off a prop.',
    category: 'tool',
    maxStack: 1,
    tool: { kind: 'rigging', power: 1, range: 6 },
  },

  // ── Materials ──────────────────────────────────────────────────────
  {
    id: 'wood_log',
    name: 'Wood Log',
    description: 'Raw timber. Saw into planks, or burn as generator fuel.',
    category: 'material',
    maxStack: 20,
    fuel: { burnSeconds: 90 },
    world: {
      shape: { type: 'cylinder', radius: 0.14, height: 0.6 },
      massKg: 5,
      color: '#7a5432',
      physgun: true,
    },
  },
  {
    id: 'tree_trunk',
    name: 'Tree Trunk',
    description: 'A whole felled trunk. Buck it into logs.',
    category: 'material',
    maxStack: 1,
    world: {
      shape: { type: 'cylinder', radius: 0.3, height: 2.9 },
      massKg: 70,
      color: '#6d4c2a',
      physgun: true,
    },
  },
  {
    id: 'wood_plank',
    name: 'Wood Plank',
    description: 'Rough-sawn lumber, good enough to build with.',
    category: 'material',
    maxStack: 50,
    fuel: { burnSeconds: 30 },
    world: {
      shape: { type: 'box', size: [0.9, 0.07, 0.28] },
      massKg: 3,
      color: '#a3814e',
      physgun: true,
    },
  },
  {
    id: 'stone',
    name: 'Stone',
    description: 'Quarried rock. Heavy and dependable.',
    category: 'material',
    maxStack: 50,
    world: {
      shape: { type: 'sphere', radius: 0.17 },
      massKg: 6,
      color: '#83878b',
      physgun: true,
    },
  },
  {
    id: 'scrap_metal',
    name: 'Scrap Metal',
    description: 'Twisted bits of salvage. The wilderness provides.',
    category: 'material',
    maxStack: 50,
    world: {
      shape: { type: 'box', size: [0.42, 0.12, 0.3] },
      massKg: 4,
      color: '#6a7076',
      physgun: true,
    },
  },
  {
    id: 'sheet_metal',
    name: 'Sheet Metal',
    description: 'Scrap hammered flat at a workbench.',
    category: 'material',
    maxStack: 20,
  },
  {
    id: 'berries',
    name: 'Wild Berries',
    description: 'Tart forest berries. A snack, or stew them at a burn barrel.',
    category: 'food',
    maxStack: 20,
    food: { hunger: 8, thirst: 4, health: 0 },
    world: {
      shape: { type: 'sphere', radius: 0.09 },
      massKg: 0.5,
      color: '#5a2a4a',
      physgun: true,
    },
  },
  {
    id: 'trail_stew',
    name: 'Trail Stew',
    description: 'Berries and bark simmered in a burn barrel. Scrapper haute cuisine.',
    category: 'food',
    maxStack: 10,
    food: { hunger: 42, thirst: 18, health: 10 },
    world: {
      shape: { type: 'cylinder', radius: 0.12, height: 0.12 },
      massKg: 1,
      color: '#7a4a2a',
      physgun: true,
    },
  },
  {
    id: 'coin',
    name: 'Bottle Cap',
    description: 'Scrap City hard currency. The merchant honors these.',
    category: 'misc',
    maxStack: 999,
    world: {
      shape: { type: 'cylinder', radius: 0.06, height: 0.02 },
      massKg: 0.2,
      color: '#c9a227',
      physgun: true,
    },
  },
  {
    id: 'salvage_core',
    name: 'Salvage Core',
    description:
      'Dense pre-collapse tech. The merchant pays a fortune — IF you get it home. Drops when you die; extract to secure it.',
    category: 'misc',
    maxStack: 5,
    valuable: {},
    world: {
      shape: { type: 'box', size: [0.24, 0.24, 0.24] },
      massKg: 8,
      color: '#4ec9b0',
      physgun: true,
    },
  },
  {
    id: 'berry_seeds',
    name: 'Berry Seeds',
    description: 'Plant in a planter box. Grows a berry crop in a few minutes.',
    category: 'seed',
    maxStack: 20,
    seed: { crop: 'berry' },
  },
  {
    id: 'planter_box',
    name: 'Planter Box',
    description: 'Soil bed. Plant seeds with E; harvest when grown.',
    category: 'building',
    maxStack: 4,
    planter: {},
    world: {
      shape: { type: 'box', size: [1.1, 0.35, 1.1] },
      massKg: 25,
      color: '#5a4632',
      physgun: true,
    },
    placeable: { maxRange: 3.5, snapStep: 0.35 },
  },
  {
    id: 'merchant_stall',
    name: "Goose's Trading Post",
    description: 'Buy and sell. The goose sees all.',
    category: 'misc',
    maxStack: 1,
    shop: { market: 'goose_post' },
    world: {
      shape: { type: 'box', size: [1.8, 1.1, 0.9] },
      massKg: 200,
      color: '#7a5a9a',
      physgun: false,
    },
  },
  {
    id: 'supply_crate',
    name: 'Supply Drop',
    description: 'Sealed pre-collapse cache. Announced when it lands. First come, first served.',
    category: 'misc',
    maxStack: 1,
    container: { slots: 6 },
    world: {
      shape: { type: 'box', size: [1.0, 0.9, 1.0] },
      massKg: 120,
      color: '#b05030',
      physgun: false,
    },
  },
  {
    id: 'rope',
    name: 'Rope',
    description: 'Braided scavenged fiber. The rigging tool spends one per tether.',
    category: 'component',
    maxStack: 20,
  },
  {
    id: 'salvaged_motor',
    name: 'Salvaged Motor',
    description: 'A rewound scrap motor. Drives one powered joint via the rigging tool.',
    category: 'component',
    maxStack: 5,
    world: {
      shape: { type: 'cylinder', radius: 0.12, height: 0.2 },
      massKg: 6,
      color: '#3a4a5a',
      physgun: true,
    },
  },

  {
    id: 'loot_bag',
    name: 'Dropped Loot',
    description: 'Somebody died carrying this. Finders keepers.',
    category: 'misc',
    maxStack: 1,
    container: { slots: 8 },
    world: {
      shape: { type: 'sphere', radius: 0.3 },
      massKg: 8,
      color: '#5a4a3a',
      physgun: true,
    },
  },

  {
    id: 'blueprint_scrap_pistol',
    name: 'Blueprint: Scrap Pistol',
    description: 'Greasy hand-drawn plans. Use (LMB) to learn the recipe for good.',
    category: 'misc',
    maxStack: 1,
    valuable: {},
    blueprint: { recipe: 'craft_scrap_pistol' },
  },
  {
    id: 'blueprint_still',
    name: 'Blueprint: Backwoods Still',
    description: "Somebody's prized still schematics. Use (LMB) to learn the recipe.",
    category: 'misc',
    maxStack: 1,
    valuable: {},
    blueprint: { recipe: 'craft_still' },
  },

  // ── Building pieces (crafted physical objects, physgun-placed) ─────
  {
    id: 'wooden_wall',
    name: 'Wooden Wall',
    description: 'A solid timber wall section. Freeze it in place.',
    category: 'building',
    maxStack: 10,
    world: {
      shape: { type: 'box', size: [2, 2.4, 0.15] },
      massKg: 55,
      color: '#8a6238',
      physgun: true,
    },
    health: {
      max: 200,
      resistance: 1,
      repair: { item: 'wood_plank', count: 1, restore: 50 },
      destroyLoot: [{ item: 'wood_plank', count: 2 }],
    },
    placeable: { maxRange: 4, snapStep: 0.5 },
  },
  {
    id: 'wooden_floor',
    name: 'Wooden Floor',
    description: 'A timber floor/roof panel.',
    category: 'building',
    maxStack: 10,
    world: {
      shape: { type: 'box', size: [2, 0.12, 2] },
      massKg: 50,
      color: '#96703f',
      physgun: true,
    },
    health: {
      max: 200,
      resistance: 1,
      repair: { item: 'wood_plank', count: 1, restore: 50 },
      destroyLoot: [{ item: 'wood_plank', count: 2 }],
    },
    placeable: { maxRange: 4, snapStep: 0.5 },
  },
  {
    id: 'wooden_beam',
    name: 'Wooden Beam',
    description: 'Framing timber for ad-hoc engineering.',
    category: 'building',
    maxStack: 20,
    world: {
      shape: { type: 'box', size: [0.15, 0.15, 2.4] },
      massKg: 25,
      color: '#7a5631',
      physgun: true,
    },
    health: {
      max: 120,
      resistance: 1,
      repair: { item: 'wood_plank', count: 1, restore: 60 },
      destroyLoot: [{ item: 'wood_plank', count: 1 }],
    },
    placeable: { maxRange: 4, snapStep: 0.25 },
  },
  {
    id: 'metal_wall',
    name: 'Metal Wall',
    description: 'Sheet-metal wall section. Serious protection.',
    category: 'building',
    maxStack: 10,
    world: {
      shape: { type: 'box', size: [2, 2.4, 0.12] },
      massKg: 70,
      color: '#67737c',
      physgun: true,
    },
    health: {
      max: 450,
      resistance: 0.6,
      repair: { item: 'sheet_metal', count: 1, restore: 90 },
      destroyLoot: [{ item: 'scrap_metal', count: 3 }],
    },
    placeable: { maxRange: 4, snapStep: 0.5 },
  },
  {
    id: 'wooden_door',
    name: 'Wooden Door',
    description: 'Plank door. Drop it, physgun it into a doorway, freeze — then E swings it.',
    category: 'building',
    maxStack: 4,
    door: { openAngle: 1.75 },
    world: {
      shape: { type: 'box', size: [1.05, 2.05, 0.09] },
      massKg: 18,
      color: '#8a6a42',
      physgun: true,
    },
    health: {
      max: 150,
      resistance: 1,
      repair: { item: 'wood_plank', count: 1, restore: 50 },
      destroyLoot: [{ item: 'wood_plank', count: 1 }],
    },
    placeable: { maxRange: 3.5, snapStep: 0.35 },
  },
  {
    id: 'storage_box',
    name: 'Storage Box',
    description: 'A lidded box for stashing goods safely outside your pockets.',
    category: 'building',
    maxStack: 4,
    container: { slots: 12 },
    world: {
      shape: { type: 'box', size: [0.9, 0.8, 0.6] },
      massKg: 45,
      color: '#6d5a3e',
      physgun: true,
    },
    health: {
      max: 150,
      resistance: 1,
      repair: { item: 'wood_plank', count: 1, restore: 50 },
      destroyLoot: [{ item: 'wood_plank', count: 2 }],
    },
    placeable: { maxRange: 3.5, snapStep: 0.35 },
  },
  {
    // Id (and workstation kind) 'campfire' is persisted in world.db entity
    // defIds and player inventories — the Scraplandia rename is display-only.
    id: 'campfire',
    name: 'Burn Barrel',
    description: 'A salvaged drum with a cook grate. Light it, cook food, stay warm.',
    category: 'building',
    maxStack: 2,
    workstation: { kind: 'campfire', range: 2.5 },
    world: {
      shape: { type: 'cylinder', radius: 0.4, height: 0.3 },
      massKg: 15,
      color: '#8c4f2f',
      physgun: true,
    },
    placeable: { maxRange: 3.5, snapStep: 0 },
  },

  // ── Combat / protection / medical ──────────────────────────────────
  {
    id: 'scrap_pistol',
    name: 'Scrap Pistol',
    description: 'Pipe, spring, and bad intentions. LMB fires, R reloads. The wilds shoot back.',
    category: 'tool',
    maxStack: 1,
    rangedWeapon: {
      damage: 22,
      range: 45,
      fireIntervalMs: 600,
      spreadDeg: 2,
      ammoItem: 'pistol_round',
      magazine: 6,
      reloadMs: 2200,
    },
  },
  {
    id: 'pistol_round',
    name: 'Pistol Rounds',
    description: 'Hand-loaded scrap casings. Fits the scrap pistol.',
    category: 'component',
    maxStack: 60,
    ammo: {},
  },
  {
    id: 'padded_jacket',
    name: 'Padded Jacket',
    description: 'Layered scrap cloth and rubber. Blunts a third of what hits you, for a while.',
    category: 'misc',
    maxStack: 1,
    armor: { reduction: 0.35, durability: 30 },
  },
  {
    id: 'bandage',
    name: 'Bandage',
    description: 'Boiled cloth strips. Stops bleeding, patches you up a little.',
    category: 'misc',
    maxStack: 10,
    medical: { heal: 12, curesBleeding: true },
  },

  // ── Farming & food ─────────────────────────────────────────────────
  {
    id: 'mudroot_seeds',
    name: 'Mudroot Cuttings',
    description: 'Plant in a planter. Grows anywhere, needs no water. Survival food.',
    category: 'seed',
    maxStack: 20,
    seed: { crop: 'mudroot' },
  },
  {
    id: 'wheat_seeds',
    name: 'Ration Wheat Seeds',
    description: 'Thirsty field grain. Mill the sheaves into flour.',
    category: 'seed',
    maxStack: 20,
    seed: { crop: 'ration_wheat' },
  },
  {
    id: 'wirevine_seeds',
    name: 'Wirevine Cuttings',
    description: 'Fiber crop. The vines braid into rope.',
    category: 'seed',
    maxStack: 20,
    seed: { crop: 'wirevine' },
  },
  {
    id: 'ember_pepper_seeds',
    name: 'Ember Pepper Seeds',
    description: 'Fussy, warmth-hungry, and worth every cap at market.',
    category: 'seed',
    maxStack: 20,
    seed: { crop: 'ember_pepper' },
  },
  {
    id: 'mudroot',
    name: 'Mudroot',
    description: 'A dense, starchy tuber. Ugly. Reliable.',
    category: 'food',
    maxStack: 20,
    food: { hunger: 22, thirst: 0, health: 2 },
    world: {
      shape: { type: 'sphere', radius: 0.12 },
      massKg: 1,
      color: '#7a5c3a',
      physgun: true,
    },
  },
  {
    id: 'wheat_sheaf',
    name: 'Wheat Sheaf',
    description: 'Cut ration wheat. The mill wants it.',
    category: 'material',
    maxStack: 20,
    world: {
      shape: { type: 'cylinder', radius: 0.12, height: 0.5 },
      massKg: 1,
      color: '#c9b04a',
      physgun: true,
    },
  },
  {
    id: 'flour',
    name: 'Flour',
    description: 'Milled ration wheat. Bake it at a burn barrel.',
    category: 'material',
    maxStack: 20,
  },
  {
    id: 'flatbread',
    name: 'Flatbread',
    description: 'Burn-barrel bread. Proper food, worth proper caps.',
    category: 'food',
    maxStack: 10,
    food: { hunger: 46, thirst: 0, health: 6 },
  },
  {
    id: 'vine_fiber',
    name: 'Vine Fiber',
    description: 'Stripped wirevine. Braids into rope.',
    category: 'component',
    maxStack: 30,
  },
  {
    id: 'ember_pepper',
    name: 'Ember Pepper',
    description: 'Blistering little fruit. Eat it if you dare; sell it if you are wise.',
    category: 'food',
    maxStack: 20,
    food: { hunger: 10, thirst: -6, health: 4 },
  },
  {
    id: 'watering_can',
    name: 'Watering Can',
    description: 'Fill from water or a tank (E), then water planters (E). Keeps crops growing.',
    category: 'tool',
    maxStack: 1,
    fluidContainer: { capacity: 8 },
  },
  {
    id: 'fertilizer',
    name: 'Compost Fertilizer',
    description: 'Rot with a purpose. E on a planted crop grows it half again as fast.',
    category: 'material',
    maxStack: 10,
    fertilizer: { boost: 1.5 },
  },

  {
    id: 'pepper_tonic',
    name: 'Pepper Tonic',
    description:
      'Ember pepper and flour mash run through a still. Burns twice. The Goose pays absurdly well and asks no questions. At-risk until extracted.',
    category: 'food',
    maxStack: 10,
    valuable: {},
    food: { hunger: 6, thirst: 10, health: 8 },
  },
  {
    id: 'copper_still',
    name: 'Backwoods Still',
    description:
      'Feed it peppers and flour; take tonic. Needs generator power. Keep it out of sight.',
    category: 'placeable',
    maxStack: 1,
    machine: { kind: 'still', inputSlots: 2, outputSlots: 2, needsPower: true },
    container: { slots: 4 },
    world: {
      shape: { type: 'cylinder', radius: 0.4, height: 1.1 },
      massKg: 90,
      color: '#8a5a3a',
      physgun: true,
    },
    health: {
      max: 160,
      resistance: 1,
      repair: { item: 'scrap_metal', count: 1, restore: 60 },
      destroyLoot: [{ item: 'sheet_metal', count: 2 }],
    },
    placeable: { maxRange: 3.5, snapStep: 0 },
  },

  // ── Vehicle parts (assembled with the rigging tool) ────────────────
  {
    id: 'cart_chassis',
    name: 'Scrap Cart Chassis',
    description:
      'A motorized flatbed. Rig wheels to it (axis or motor links), load fuel in the trunk, E to drive.',
    category: 'placeable',
    maxStack: 1,
    vehiclePart: { part: 'chassis', power: 5200, topSpeed: 11 },
    container: { slots: 6 },
    world: {
      shape: { type: 'box', size: [1.5, 0.45, 2.3] },
      massKg: 160,
      color: '#5a5248',
      physgun: true,
    },
    health: {
      max: 300,
      resistance: 0.8,
      repair: { item: 'scrap_metal', count: 1, restore: 60 },
      destroyLoot: [
        { item: 'scrap_metal', count: 4 },
        { item: 'sheet_metal', count: 2 },
      ],
    },
    placeable: { maxRange: 4, snapStep: 0 },
  },
  {
    id: 'cart_wheel',
    name: 'Cart Wheel',
    description: 'Banded scrap wheel. Rig to a chassis with an axis link.',
    category: 'placeable',
    maxStack: 4,
    vehiclePart: { part: 'wheel' },
    world: {
      shape: { type: 'cylinder', radius: 0.38, height: 0.24 },
      massKg: 16,
      color: '#3a3a3a',
      physgun: true,
    },
    placeable: { maxRange: 4, snapStep: 0 },
  },

  // ── Utility props (power / water) ──────────────────────────────────
  {
    id: 'scrap_generator',
    name: 'Scrap Generator',
    description:
      'Burns logs or planks from its hopper and powers nearby machines. Loud, smelly, essential.',
    category: 'placeable',
    maxStack: 1,
    container: { slots: 4 },
    powerProducer: { radius: 10 },
    world: {
      shape: { type: 'box', size: [0.9, 0.9, 0.7] },
      massKg: 120,
      color: '#4a4a52',
      physgun: true,
    },
    health: {
      max: 220,
      resistance: 0.8,
      repair: { item: 'scrap_metal', count: 1, restore: 60 },
      destroyLoot: [{ item: 'scrap_metal', count: 4 }],
    },
    placeable: { maxRange: 3.5, snapStep: 0 },
  },
  {
    id: 'water_tank',
    name: 'Water Tank',
    description: 'Catches rain; fillable by can. Sprinklers drink from it.',
    category: 'placeable',
    maxStack: 2,
    waterTank: { capacity: 40 },
    world: {
      shape: { type: 'cylinder', radius: 0.5, height: 1.2 },
      massKg: 60,
      color: '#3a5a6a',
      physgun: true,
    },
    health: {
      max: 140,
      resistance: 1,
      repair: { item: 'scrap_metal', count: 1, restore: 70 },
      destroyLoot: [{ item: 'scrap_metal', count: 2 }],
    },
    placeable: { maxRange: 3.5, snapStep: 0 },
  },
  {
    id: 'sprinkler',
    name: 'Sprinkler',
    description: 'Waters every planter around it, drawing from a nearby tank.',
    category: 'placeable',
    maxStack: 4,
    sprinkler: { radius: 5, tankRange: 6 },
    world: {
      shape: { type: 'cylinder', radius: 0.1, height: 0.5 },
      massKg: 8,
      color: '#5a7a8a',
      physgun: true,
    },
    placeable: { maxRange: 3.5, snapStep: 0.35 },
  },

  // ── Machines (unattended production) ───────────────────────────────
  {
    id: 'sawmill',
    name: 'Sawmill',
    description:
      'Feed it logs; take lumber. Needs a running generator nearby. The heart of a timber business.',
    category: 'placeable',
    maxStack: 1,
    machine: { kind: 'sawmill', inputSlots: 3, outputSlots: 3, needsPower: true },
    container: { slots: 6 },
    world: {
      shape: { type: 'box', size: [1.4, 1.0, 0.9] },
      massKg: 160,
      color: '#8a6a4a',
      physgun: true,
    },
    health: {
      max: 260,
      resistance: 0.8,
      repair: { item: 'wood_plank', count: 2, restore: 60 },
      destroyLoot: [
        { item: 'scrap_metal', count: 3 },
        { item: 'wood_plank', count: 3 },
      ],
    },
    placeable: { maxRange: 3.5, snapStep: 0 },
  },
  {
    id: 'grain_mill',
    name: 'Grain Mill',
    description: 'Hand-cranked stone mill. Wheat sheaves in, flour out. No power needed.',
    category: 'placeable',
    maxStack: 1,
    machine: { kind: 'mill', inputSlots: 2, outputSlots: 2, needsPower: false },
    container: { slots: 4 },
    world: {
      shape: { type: 'cylinder', radius: 0.45, height: 1.0 },
      massKg: 140,
      color: '#8a8a82',
      physgun: true,
    },
    health: {
      max: 200,
      resistance: 0.9,
      repair: { item: 'stone', count: 2, restore: 60 },
      destroyLoot: [{ item: 'stone', count: 4 }],
    },
    placeable: { maxRange: 3.5, snapStep: 0 },
  },

  // ── Props / stations ───────────────────────────────────────────────
  {
    id: 'wooden_crate',
    name: 'Wooden Crate',
    description: 'A sturdy crate. Stack it, hide behind it, build with it.',
    category: 'placeable',
    maxStack: 4,
    world: {
      shape: { type: 'box', size: [0.7, 0.7, 0.7] },
      massKg: 35,
      color: '#a5713a',
      physgun: true,
    },
    health: {
      max: 100,
      resistance: 1,
      repair: { item: 'wood_plank', count: 1, restore: 50 },
      destroyLoot: [{ item: 'wood_plank', count: 1 }],
    },
    placeable: { maxRange: 3.5, snapStep: 0.35 },
  },
  {
    id: 'metal_barrel',
    name: 'Metal Barrel',
    description: 'Dented but serviceable.',
    category: 'placeable',
    maxStack: 2,
    world: {
      shape: { type: 'cylinder', radius: 0.3, height: 0.9 },
      massKg: 85,
      color: '#5b6b73',
      physgun: true,
    },
    health: {
      max: 180,
      resistance: 0.8,
      destroyLoot: [{ item: 'scrap_metal', count: 2 }],
    },
    placeable: { maxRange: 3.5, snapStep: 0 },
  },
  {
    id: 'workbench',
    name: 'Workbench',
    description: 'A flat surface and a vice. Unlocks serious crafting.',
    category: 'placeable',
    maxStack: 1,
    world: {
      shape: { type: 'box', size: [1.2, 0.9, 0.7] },
      massKg: 90,
      color: '#7a5c3e',
      physgun: true,
    },
    placeable: { maxRange: 3.5, snapStep: 0 },
    workstation: { kind: 'workbench', range: 3 },
  },
]

/** Items granted once to every new (or migrated) player. */
export const STARTER_ITEMS: readonly { item: string; count: number }[] = [
  { item: 'physgun', count: 1 },
]
