import type { ResourceNodeType } from '../schema/resourceNode.js'

/**
 * Gathering content. Hand-gatherable pile nodes (branches, loose stones,
 * scrap) bootstrap the tool economy: piles -> planks -> stone tools ->
 * efficient tree/deposit harvesting.
 */
export const RESOURCE_NODES: ResourceNodeType[] = [
  {
    id: 'oak_tree',
    name: 'Oak Tree',
    item: 'wood_log',
    amount: 12,
    perUse: 1,
    requiredTool: 'axe',
    respawnSeconds: 180,
    skill: 'woodcutting',
    xpPerGather: 6,
    visual: 'tree',
    bodyShape: { type: 'cylinder', radius: 0.35, height: 3.2 },
    bodyOffsetY: 1.6,
  },
  {
    id: 'stone_deposit',
    name: 'Stone Deposit',
    item: 'stone',
    amount: 16,
    perUse: 1,
    requiredTool: 'pickaxe',
    respawnSeconds: 240,
    skill: 'mining',
    xpPerGather: 6,
    visual: 'rock',
    bodyShape: { type: 'box', size: [1.4, 1.1, 1.4] },
    bodyOffsetY: 0.55,
  },
  {
    id: 'scrap_pile',
    name: 'Scrap Pile',
    item: 'scrap_metal',
    amount: 10,
    perUse: 2,
    respawnSeconds: 300,
    skill: 'scavenging',
    xpPerGather: 5,
    visual: 'scrap',
    bodyShape: { type: 'box', size: [0.9, 0.5, 0.9] },
    bodyOffsetY: 0.25,
  },
  {
    id: 'berry_bush',
    name: 'Berry Bush',
    item: 'berries',
    amount: 6,
    perUse: 2,
    respawnSeconds: 150,
    skill: 'scavenging',
    xpPerGather: 3,
    visual: 'branches',
    bodyShape: { type: 'box', size: [0.9, 0.8, 0.9] },
    bodyOffsetY: 0.4,
  },
  {
    id: 'branch_pile',
    name: 'Fallen Branches',
    item: 'wood_log',
    amount: 4,
    perUse: 1,
    respawnSeconds: 120,
    skill: 'woodcutting',
    xpPerGather: 3,
    visual: 'branches',
    bodyShape: { type: 'box', size: [0.8, 0.35, 0.8] },
    bodyOffsetY: 0.18,
  },
  {
    id: 'loose_stones',
    name: 'Loose Stones',
    item: 'stone',
    amount: 5,
    perUse: 1,
    respawnSeconds: 120,
    skill: 'mining',
    xpPerGather: 3,
    visual: 'stones',
    bodyShape: { type: 'box', size: [0.7, 0.3, 0.7] },
    bodyOffsetY: 0.15,
  },
]
